### ISSUE TITLE
still providing config.sample.js instead of config.sample.json

### ISSUE THREAD

**Issue by pbanj** [kanadeko/Kuro#27]
as the title says

**Comment by brussell98** [comment]
JS objects have more features than the JSON format does.

For example: JSON does not allow single quotes, trailing commas, or 0xff66aa style numbers

**Comment by Pitu** [comment]
That is true, but he is referring to the fact that kuro.js loads a json file as config but the example file im providing is actually js and not json. The reason I'm using json is because if you install Kuro from [kuro-cli](https://github.com/Pitu/Kuro-cli), after the setup it writes the whole config object as a json since it's easier than writing it to a js one, afaik.

**Comment by Pitu** [comment]
Fixed on 4ea2050
